export const LANDING = '/'
export const HOME = '/home'
export const LOGIN = '/login'
export const LOGOUT = '/logout'
export const SIGNIN = '/signin'
export const POD = '/pod'
export const MAINHALL = '/mainhall'
